"""
X-Correlation-Id propagation middleware and context variable.

WHY: In a distributed system, a single client request spawns calls across
multiple services. Without a shared trace ID, it is impossible to connect
logs from api-gateway → payment-service → decision-hub → ledger-mock.

The correlation_id is:
  1. Generated by api-gateway if not present in the incoming request
  2. Propagated downstream via X-Correlation-Id HTTP header
  3. Stored in a ContextVar so any log call within the request has access

ContextVar is used (not a global) because FastAPI is async — multiple
requests are in flight simultaneously in the same process.
"""

import uuid
from contextvars import ContextVar
from typing import Callable

from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware

CORRELATION_ID_HEADER = "X-Correlation-Id"

_correlation_id: ContextVar[str] = ContextVar("correlation_id", default="")


def get_correlation_id() -> str:
    return _correlation_id.get()


def set_correlation_id(value: str) -> None:
    _correlation_id.set(value)


class CorrelationMiddleware(BaseHTTPMiddleware):
    """
    Reads X-Correlation-Id from incoming request (or generates one),
    stores it in ContextVar, and echoes it back in the response header.
    """

    def __init__(self, app, generate_if_missing: bool = False):
        super().__init__(app)
        self.generate_if_missing = generate_if_missing

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        correlation_id = request.headers.get(CORRELATION_ID_HEADER)
        if not correlation_id and self.generate_if_missing:
            correlation_id = str(uuid.uuid4())
        if correlation_id:
            set_correlation_id(correlation_id)

        response = await call_next(request)

        if correlation_id:
            response.headers[CORRELATION_ID_HEADER] = correlation_id

        return response
